export const BAN_WORDS = [
    'Just Chatting',
    'IRL',
    'Sports',
    'ASMR',
    'Music',
    'Slots',
    'Art',
    'Games + Demos',
    'Retro',
    'Animals, Aquariums, and Zoos',
    'Always On',
    'Kings League',
    'Special Events',
    'Chess',
    'Talk Shows & Podcasts',
    'Politics',
    'Software and Game Development',
    'Food & Drink',
    'Makers & Crafting',
    'Poker'
]