import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Steam Suggester",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head prefix="og: http://ogp.me/ns# website: http://ogp.me/ns/website#">
        <title>Steam Suggester</title>
        <meta name="description" content="Steam game suggestions based on trends" />

        {/* OGP */}
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Steam Suggester" />
        <meta property="og:description" content="TwitchとSteamを組み合わせたゲーム提案を可視化するウェブサイト。最適なゲーム体験を見つけよう！" />
        <meta property="og:url" content={process.env.NEXT_PUBLIC_CURRENT_URL} />
        <meta property="og:site_name" content="Steam Suggester" />
        <meta property="og:image" content={`${process.env.NEXT_PUBLIC_CURRENT_URL}/ogp.png`} />
        <meta property="og:locale" content="ja_JP" />

        <meta name="keywords" content="Steam, Twitch, Game Network, Game Recommendations, Visualization" />

        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
